server:
  address: 0.0.0.0
  port: 8080

kafka:
  bootstrap-servers: kafka:9092

spring:
  main:
    web-application-type: none
  jmx:
    enabled: true

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"