kafka:
  bootstrap-servers: localhost:9092

spring:
  jmx:
    enabled: true

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"
